### ISSUE TITLE
Any body help for running ?

### ISSUE THREAD

**Issue by prep52** [agourk/crabada#2]
Can you help with what needs to be done to get it to work? Also, although I'm not sure, there are deficiencies in the scripts folder. can you share them too? fokustekin@gmail.com

**Comment by agourk** [comment]
Hey, I am sorry I didn't mean to make this repo public. I will make it private soon, so if you'd like to clone it, do it asap please.
As for how to run it, first run `npm install`.
Then create a dot env file (.env) and in it declare the PRIVATE_KEY variable as such: `PRIVATE_KEY=your_private_key_here`. In `hardhat.config.ts` scroll all the way down and find the `mainnet` object  and add `process.env.PRIVATE_KEY` in the `accounts` list
When all that is done, you can run the script with `npx hardhat run scripts/run.ts --network mainnet`.

**Comment by prep52** [comment]
yes the yolo strategy file is missing . It was not my intention to use your file without your permission . If you have permission, please contact me with my e-mail address. fokustekin@gmail.com

**Comment by agourk** [comment]
There is no `yolo strategy` file. That strategy is present in the `scripts/strategies.ts` script. You have my permission, I'll close the repo tonight though.
